name:                dffinder
version:             0.1.0.0
github:              "mayconamaro/dffinder"
license:             BSD3
author:              "Maycon Amaro"
maintainer:          "maycon.amaro@decom.ufop.br"
copyright:           "2020 Maycon Amaro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Find duplicate files in a folder and its subfolders
# category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dffinder#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3
- cond >= 0.4
- filepath >= 1.4
- extra
- bytestring
- pureMD5 >= 2.1

library:
  source-dirs: src

executables:
  dffinder:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dffinder

tests:
  dffinder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dffinder
